# Site settings
title: Aaron Hammer
description: The most awesome website for Aaron Hammer and his projects.
keywords: "Full, Stack, Developer, Aaron, Hammer, Aaron Hammer, Coding, Awesome"
author: "Aaron Hammer"
url: "http://aaronha.com"

# User settings
username: Aaron Hammer
user_title: Full Stack Developer
email: aaronmathewhammer@gmail.com
github_username: aar118
linkedin_username: aaron-mathew-hammer

# Google-analytics
google-analytics:
  id: "UA-77847929-2"

exclude: ['package.json', 'src' , 'node_modules']
