# Site settings
title: Aaron Hammer
description: It's Hammer Time
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aaron Hammer
user_description: Programming is amazing. I love doing multiple kinds of programming, from software to client-side to server-side. It's especially great when my programming is used to help otber people.
user_title: Full Stack Developer
email: aaronmathewhammer@gmail.com
github_username: aar118
linkedin_username: aaron-mathew-hammer

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
