# Site settings
title: Aaron Hammer
description: The most awesome website for Aaron Hammer and his projects.
keywords: "Full, Stack, Developer, Aaron, Hammer, Aaron Hammer, Coding, Awesome"
author: "Aaron Hammer"

# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://aaronha.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aaron Hammer
user_title: Full Stack Developer
email: aaronmathewhammer@gmail.com
github_username: aar118
linkedin_username: aaron-mathew-hammer

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
